require:
  - rubocop-jekyll
  - rubocop-minitest

inherit_gem:
  rubocop-jekyll: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.7
  SuggestExtensions: false
  Exclude:
    - vendor/**/*

Layout/LineLength:
  Exclude:
    - lib/jekyll-archives-v2.rb
    - lib/jekyll-archives-v2/archive.rb
    - test/**/*.rb

Metrics/BlockLength:
  Exclude:
    - test/**/*.rb

Minitest/AssertKindOf:
  Enabled: true
Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: true
