title: Jekyll Archives V2
description: Automatically generate collections archives by dates, tags, ,categories, or any other array variable.

permalink: pretty

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

theme: jekyll-theme-primer
