name: Deploy site

on:
  push:
    branches:
      - main
    paths:
      - "site/**"
  pull_request:
    branches:
      - main
    paths:
      - "site/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    # available images: https://github.com/actions/runner-images#available-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Setup Ruby 💎
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.5"
          bundler-cache: true
      - name: Install and Build 🔧
        run: |
          cd site/
          export JEKYLL_ENV=production
          bundle exec jekyll build
      - name: Deploy 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site/_site
